apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 582498371272.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 582498371272.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: b558cd41
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
